import { useMemo, useRef, useState } from 'react';
import { ClipboardCopy, Download, FolderLock, RefreshCw, ShieldCheck, Sparkles, Upload } from 'lucide-react';
import { createArtifactManifestEntry, createProjectManifest } from '@phioffice369/core';
import { scanLocalExportReceipts } from '../lib/localReceipts.js';
import './PhiVaultLite.css';

function canUseLocalStorage() {
  try {
    return typeof window !== 'undefined' && Boolean(window.localStorage);
  } catch {
    return false;
  }
}

function parseStoredValue(key) {
  try {
    return JSON.parse(window.localStorage.getItem(key));
  } catch {
    return null;
  }
}

function kindFromKey(key) {
  if (key.includes(':phiwrite:')) return { kind: 'document', app: 'PhiWrite' };
  if (key.includes(':phigrid:')) return { kind: 'grid', app: 'PhiGrid' };
  if (key.includes(':export_receipt:')) return { kind: 'export_receipt', app: 'PhiVault' };
  return { kind: 'vault_item', app: 'PhiVault' };
}

function titleFromDraft(key, value) {
  if (value?.title) return value.title;
  if (value?.filename) return value.filename;
  return key.split(':').at(-1) ?? 'Untitled artifact';
}

function scanLocalArtifacts() {
  if (!canUseLocalStorage()) return [];

  return Object.keys(window.localStorage)
    .filter((key) => key.startsWith('phioffice369:'))
    .filter((key) => !key.startsWith('phioffice369:export_receipt:'))
    .map((key) => {
      const storedValue = parseStoredValue(key);
      const { kind, app } = kindFromKey(key);
      return createArtifactManifestEntry({
        artifactId: key.replaceAll(':', '_'),
        title: titleFromDraft(key, storedValue),
        kind,
        app,
        path: key,
        labels: storedValue?.activeLabelId ? [storedValue.activeLabelId] : [],
        sourceTemplateId: storedValue?.templateId ?? null,
        status: 'local-draft',
      });
    });
}

function exportReceiptToArtifact({ key, receipt }) {
  return createArtifactManifestEntry({
    artifactId: key.replaceAll(':', '_'),
    title: receipt.filename ?? `${receipt.sourceApp} ${receipt.format} export`,
    kind: 'export_receipt',
    app: receipt.sourceApp ?? 'PhiVault',
    path: key,
    labels: [],
    receipts: [receipt],
    sourceTemplateId: null,
    status: 'exported',
  });
}

function scanContinuityArtifacts() {
  const drafts = scanLocalArtifacts();
  const exportArtifacts = scanLocalExportReceipts().map(exportReceiptToArtifact);
  return [...drafts, ...exportArtifacts];
}

function downloadJson(filename, payload) {
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function groupArtifactsByApp(artifacts) {
  return artifacts.reduce((groups, artifact) => {
    const key = artifact.app ?? 'Unknown';
    return { ...groups, [key]: [...(groups[key] ?? []), artifact] };
  }, {});
}

export default function PhiVaultLite() {
  const fileInputRef = useRef(null);
  const [artifacts, setArtifacts] = useState(() => scanContinuityArtifacts());
  const [status, setStatus] = useState('Local manifest ready');
  const [copyStatus, setCopyStatus] = useState('');
  const [importedManifest, setImportedManifest] = useState(null);

  const manifest = useMemo(() => createProjectManifest({
    projectId: 'local_phioffice369_project',
    title: 'Local PhiOffice369 Workspace',
    description: 'Browser-local project manifest generated by PhiVault-lite.',
    owner: 'local-browser-user',
    tags: ['local-first', 'prototype', 'phioffice369'],
    artifacts,
  }), [artifacts]);

  const groupedArtifacts = useMemo(() => groupArtifactsByApp(artifacts), [artifacts]);
  const appGroupCount = Object.keys(groupedArtifacts).length;
  const exportReceiptCount = artifacts.filter((artifact) => artifact.kind === 'export_receipt').length;

  function refreshArtifacts() {
    const nextArtifacts = scanContinuityArtifacts();
    setArtifacts(nextArtifacts);
    setStatus(`Scanned ${nextArtifacts.length} continuity item${nextArtifacts.length === 1 ? '' : 's'}`);
  }

  function exportManifest() {
    downloadJson('phioffice369-local-project-manifest.json', manifest);
    setStatus('Project manifest exported');
  }

  async function copyManifest() {
    try {
      await navigator.clipboard.writeText(JSON.stringify(manifest, null, 2));
      setCopyStatus('Manifest JSON copied');
    } catch {
      setCopyStatus('Copy unavailable in this browser');
    }
  }

  function triggerImport() {
    fileInputRef.current?.click();
  }

  async function importManifest(event) {
    const file = event.target.files?.[0];
    if (!file) return;

    try {
      const text = await file.text();
      const parsed = JSON.parse(text);
      if (!parsed.schema?.startsWith('phioffice369.project_manifest.')) {
        setStatus('Imported file is not a PhiOffice369 project manifest');
        return;
      }
      setImportedManifest(parsed);
      setStatus(`Imported preview: ${parsed.title ?? 'Untitled manifest'}`);
    } catch {
      setStatus('Could not read that manifest JSON');
    } finally {
      event.target.value = '';
    }
  }

  return (
    <section className="phivault-lite section-block fade-in">
      <div className="vault-hero panel">
        <FolderLock aria-hidden="true" />
        <div>
          <p className="eyebrow">PhiVault-lite</p>
          <h2>Local project continuity</h2>
          <p>Scan browser-local drafts, grids, and export receipts; preview imported manifests; and export project continuity JSON.</p>
          <p className="vault-status">{status}</p>
          {copyStatus && <p className="vault-copy-status">{copyStatus}</p>}
        </div>
        <div className="vault-actions">
          <button type="button" onClick={refreshArtifacts}><RefreshCw aria-hidden="true" /> Refresh scan</button>
          <button type="button" onClick={copyManifest}><ClipboardCopy aria-hidden="true" /> Copy manifest</button>
          <button type="button" onClick={triggerImport}><Upload aria-hidden="true" /> Import preview</button>
          <button type="button" onClick={exportManifest}><Download aria-hidden="true" /> Export manifest</button>
          <input ref={fileInputRef} className="vault-file-input" type="file" accept="application/json,.json" onChange={importManifest} />
        </div>
      </div>

      <div className="vault-grid">
        <aside className="panel vault-summary">
          <ShieldCheck aria-hidden="true" />
          <h3>Manifest envelope</h3>
          <code>{manifest.schema}</code>
          <div className="vault-stat-grid">
            <div><strong>{artifacts.length}</strong><span>items</span></div>
            <div><strong>{exportReceiptCount}</strong><span>exports</span></div>
            <div><strong>{appGroupCount}</strong><span>app groups</span></div>
            <div><strong>{importedManifest ? 1 : 0}</strong><span>imports</span></div>
          </div>
          <p>Nothing is uploaded. This view only reads local browser storage created by the prototype and imported JSON files you select.</p>

          {importedManifest && (
            <div className="import-preview">
              <h3>Imported preview</h3>
              <p>{importedManifest.title}</p>
              <code>{importedManifest.schema}</code>
              <span>{importedManifest.artifacts?.length ?? 0} artifacts</span>
            </div>
          )}
        </aside>

        <section className="panel vault-artifacts">
          <div className="vault-section-heading">
            <div>
              <p className="eyebrow">Local continuity</p>
              <h2>Detected drafts, grids, and exports</h2>
            </div>
          </div>

          {artifacts.length === 0 ? (
            <div className="empty-vault">
              <Sparkles aria-hidden="true" />
              <h3>No local continuity items yet</h3>
              <p>Open a template, make a small edit, export a file, and return here to refresh the vault scan.</p>
            </div>
          ) : (
            <div className="artifact-groups">
              {Object.entries(groupedArtifacts).map(([app, appArtifacts]) => (
                <section className="artifact-group" key={app}>
                  <div className="artifact-group-heading">
                    <h3>{app}</h3>
                    <span>{appArtifacts.length} item{appArtifacts.length === 1 ? '' : 's'}</span>
                  </div>
                  <div className="artifact-list">
                    {appArtifacts.map((artifact) => (
                      <article className={`artifact-row ${artifact.kind === 'export_receipt' ? 'export-row' : ''}`} key={artifact.artifactId}>
                        <div>
                          <span>{artifact.app} · {artifact.kind}</span>
                          <h3>{artifact.title}</h3>
                          <p>{artifact.path}</p>
                        </div>
                        <div className="artifact-badges">
                          <span>{artifact.status}</span>
                          {artifact.receipts?.[0]?.format && <span>{artifact.receipts[0].format}</span>}
                          {artifact.labels.map((label) => <span key={label}>{label}</span>)}
                        </div>
                      </article>
                    ))}
                  </div>
                </section>
              ))}
            </div>
          )}
        </section>
      </div>
    </section>
  );
}
