import { useEffect, useMemo, useRef, useState } from 'react';
import { ClipboardCopy, Database, Download, FolderLock, RefreshCw, Search, ShieldCheck, Sparkles, Upload, X } from 'lucide-react';
import { createProjectManifest } from '@phioffice369/core';
import { createWorkspaceBackupPayload, isWorkspaceBackupPayload, restoreWorkspaceBackupPayload } from '../lib/emergencyBackups.js';
import { normalizeProjectFolder, parseTagInput, writeArtifactMetadata } from '../lib/localArtifactMetadata.js';
import {
  buildExportTimeline,
  filterArtifacts,
  formatExportTime,
  groupArtifactsByApp,
  scanContinuityArtifacts,
  uniqueArtifactValues,
} from '../lib/localArtifactRegistry.js';
import { getStorageStatus, getStorageStatusMessage } from '../lib/storageDiagnostics.js';
import { createBrowserStorageAdapter } from '../lib/storageAdapters.js';
import { createStorageMigrationPlan, migrateStorage, summarizeMigrationPlan } from '../lib/storageMigration.js';
import { createStorageMigrationReport, getMigrationConflictKeys } from '../lib/storageMigrationReports.js';
import './PhiVaultLite.css';
import './PhiVaultMigration.css';

function downloadJson(filename, payload) {
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function detailValue(value, fallback = '—') {
  if (Array.isArray(value)) return value.length ? value.join(', ') : fallback;
  return value || fallback;
}

function updateArtifactInList(artifacts, artifactId, updater) {
  return artifacts.map((artifact) => (artifact.artifactId === artifactId ? updater(artifact) : artifact));
}

export default function PhiVaultLite() {
  const fileInputRef = useRef(null);
  const [artifacts, setArtifacts] = useState(() => scanContinuityArtifacts());
  const [status, setStatus] = useState('Local manifest ready');
  const [copyStatus, setCopyStatus] = useState('');
  const [storageStatus, setStorageStatus] = useState(null);
  const [migrationPlan, setMigrationPlan] = useState(null);
  const [migrationResult, setMigrationResult] = useState(null);
  const [importedManifest, setImportedManifest] = useState(null);
  const [importedBackup, setImportedBackup] = useState(null);
  const [query, setQuery] = useState('');
  const [appFilter, setAppFilter] = useState('all');
  const [kindFilter, setKindFilter] = useState('all');
  const [projectFilter, setProjectFilter] = useState('all');
  const [selectedArtifact, setSelectedArtifact] = useState(null);
  const [tagInput, setTagInput] = useState('');
  const [projectInput, setProjectInput] = useState('');

  const filteredArtifacts = useMemo(() => filterArtifacts(artifacts, query, appFilter, kindFilter, projectFilter), [appFilter, artifacts, kindFilter, projectFilter, query]);
  const migrationSummary = useMemo(() => (migrationPlan ? summarizeMigrationPlan(migrationPlan) : null), [migrationPlan]);
  const migrationReport = useMemo(() => (migrationPlan ? createStorageMigrationReport({ plan: migrationPlan, result: migrationResult }) : null), [migrationPlan, migrationResult]);
  const migrationConflictKeys = useMemo(() => getMigrationConflictKeys(migrationPlan, 5), [migrationPlan]);

  const manifest = useMemo(() => createProjectManifest({
    projectId: 'local_phioffice369_project',
    title: 'Local PhiOffice369 Workspace',
    description: 'Browser-local project manifest generated by PhiVault-lite.',
    owner: 'local-browser-user',
    tags: ['local-first', 'prototype', 'phioffice369'],
    artifacts,
  }), [artifacts]);

  const groupedArtifacts = useMemo(() => groupArtifactsByApp(filteredArtifacts), [filteredArtifacts]);
  const exportTimeline = useMemo(() => buildExportTimeline(artifacts), [artifacts]);
  const exportReceiptCount = exportTimeline.length;
  const appOptions = useMemo(() => uniqueArtifactValues(artifacts, 'app'), [artifacts]);
  const kindOptions = useMemo(() => uniqueArtifactValues(artifacts, 'kind'), [artifacts]);
  const projectOptions = useMemo(() => uniqueArtifactValues(artifacts, 'projectFolder'), [artifacts]);
  const selectedReceipt = selectedArtifact?.receipts?.[0] ?? null;
  const projectFolderCount = projectOptions.filter((option) => option !== 'all').length;

  function createMigrationAdapters() {
    return {
      sourceAdapter: createBrowserStorageAdapter(window, { preferredBackend: 'localStorage' }),
      targetAdapter: createBrowserStorageAdapter(window, { preferredBackend: 'indexedDB' }),
    };
  }

  async function refreshStorageStatus() {
    const nextStatus = await getStorageStatus(window);
    setStorageStatus(nextStatus);
  }

  useEffect(() => {
    refreshStorageStatus();
  }, []);

  function refreshArtifacts() {
    const nextArtifacts = scanContinuityArtifacts();
    setArtifacts(nextArtifacts);
    setSelectedArtifact(null);
    setTagInput('');
    setProjectInput('');
    refreshStorageStatus();
    setStatus(`Scanned ${nextArtifacts.length} continuity item${nextArtifacts.length === 1 ? '' : 's'}`);
  }

  function resetFilters() {
    setQuery('');
    setAppFilter('all');
    setKindFilter('all');
    setProjectFilter('all');
    setStatus('Vault filters reset');
  }

  function selectArtifact(artifact) {
    setSelectedArtifact(artifact);
    setTagInput((artifact.tags ?? []).join(', '));
    setProjectInput(artifact.projectFolder ?? '');
  }

  function exportManifest() {
    downloadJson('phioffice369-local-project-manifest.json', manifest);
    setStatus('Project manifest exported');
  }

  function exportWorkspaceBackup() {
    const payload = createWorkspaceBackupPayload({ storage: window.localStorage, manifest });
    const safeTimestamp = payload.createdAt.replace(/[:.]/g, '-');
    downloadJson(`phioffice369-workspace-backup-${safeTimestamp}.json`, payload);
    setStatus(`Workspace backup exported with ${payload.storageSnapshot.length} local item${payload.storageSnapshot.length === 1 ? '' : 's'}`);
  }

  function exportMigrationReport() {
    if (!migrationReport) {
      setStatus('Create a migration plan before exporting a report');
      return;
    }

    const safeTimestamp = migrationReport.createdAt.replace(/[:.]/g, '-');
    downloadJson(`phioffice369-storage-migration-report-${safeTimestamp}.json`, migrationReport);
    setStatus('Redacted storage migration report exported');
  }

  async function planIndexedDbMigration() {
    if (!window.indexedDB) {
      setStatus('IndexedDB is not available in this browser');
      return;
    }

    try {
      const { sourceAdapter, targetAdapter } = createMigrationAdapters();
      const plan = await createStorageMigrationPlan({ sourceAdapter, targetAdapter });
      setMigrationPlan(plan);
      setMigrationResult(null);
      setStatus(`Migration plan ready: ${plan.missingInTargetCount} missing, ${plan.alreadySyncedCount} synced, ${plan.conflictCount} conflicts`);
    } catch (error) {
      setStatus(`Could not create migration plan: ${error?.message ?? 'unknown error'}`);
    }
  }

  async function copyMissingToIndexedDb() {
    if (!window.indexedDB) {
      setStatus('IndexedDB is not available in this browser');
      return;
    }

    try {
      const { sourceAdapter, targetAdapter } = createMigrationAdapters();
      const { plan, result } = await migrateStorage({ sourceAdapter, targetAdapter, dryRun: false, overwrite: false });
      setMigrationPlan(plan);
      setMigrationResult(result);
      await refreshStorageStatus();
      setStatus(`IndexedDB safe copy complete: ${result.appliedCount} copied, ${result.skippedCount} skipped, ${result.conflictCount} conflicts`);
    } catch (error) {
      setStatus(`Could not copy to IndexedDB: ${error?.message ?? 'unknown error'}`);
    }
  }

  function restoreImportedBackup() {
    if (!importedBackup) return;
    const result = restoreWorkspaceBackupPayload(importedBackup, window.localStorage);
    if (!result.ok) {
      setStatus(`Backup restore failed: ${result.reason}`);
      return;
    }

    const nextArtifacts = scanContinuityArtifacts();
    setArtifacts(nextArtifacts);
    setSelectedArtifact(null);
    setTagInput('');
    setProjectInput('');
    refreshStorageStatus();
    setStatus(`Restored ${result.restored} local item${result.restored === 1 ? '' : 's'} from workspace backup`);
  }

  async function copyJson(payload, label) {
    try {
      await navigator.clipboard.writeText(JSON.stringify(payload, null, 2));
      setCopyStatus(`${label} copied`);
    } catch {
      setCopyStatus('Copy unavailable in this browser');
    }
  }

  function copyManifest() {
    copyJson(manifest, 'Manifest JSON');
  }

  function copyMigrationReport() {
    if (!migrationReport) {
      setStatus('Create a migration plan before copying a report');
      return;
    }
    copyJson(migrationReport, 'Redacted migration report');
  }

  function copySelectedArtifact() {
    if (!selectedArtifact) return;
    copyJson(selectedArtifact, 'Artifact JSON');
  }

  function copySelectedReceipt() {
    if (!selectedReceipt) return;
    copyJson(selectedReceipt, 'Receipt JSON');
  }

  function updateSelectedMetadata(metadata, statusMessage) {
    if (!selectedArtifact) return;
    const nextMetadata = writeArtifactMetadata(selectedArtifact.artifactId, metadata);
    const updateWithMetadata = (artifact) => ({
      ...artifact,
      tags: nextMetadata.tags,
      projectFolder: nextMetadata.projectFolder,
      metadata: {
        ...(artifact.metadata ?? {}),
        tags: nextMetadata.tags,
        projectFolder: nextMetadata.projectFolder,
        metadataUpdatedAt: nextMetadata.updatedAt,
      },
    });

    setArtifacts((currentArtifacts) => updateArtifactInList(currentArtifacts, selectedArtifact.artifactId, updateWithMetadata));
    setSelectedArtifact((currentSelected) => (currentSelected ? updateWithMetadata(currentSelected) : currentSelected));
    setTagInput(nextMetadata.tags.join(', '));
    setProjectInput(nextMetadata.projectFolder ?? '');
    refreshStorageStatus();
    setStatus(statusMessage(nextMetadata));
  }

  function saveSelectedTags() {
    const tags = parseTagInput(tagInput);
    updateSelectedMetadata({ tags }, (metadata) => `Saved ${metadata.tags.length} local tag${metadata.tags.length === 1 ? '' : 's'}`);
  }

  function saveSelectedProjectFolder() {
    const projectFolder = normalizeProjectFolder(projectInput);
    updateSelectedMetadata({ projectFolder }, (metadata) => (metadata.projectFolder ? `Assigned to ${metadata.projectFolder}` : 'Removed project folder assignment'));
  }

  function clearSelectedTags() {
    setTagInput('');
  }

  function clearProjectInput() {
    setProjectInput('');
  }

  function triggerImport() {
    fileInputRef.current?.click();
  }

  async function importManifest(event) {
    const file = event.target.files?.[0];
    if (!file) return;

    try {
      const text = await file.text();
      const parsed = JSON.parse(text);
      if (isWorkspaceBackupPayload(parsed)) {
        setImportedBackup(parsed);
        setImportedManifest(parsed.manifest ?? null);
        setStatus(`Workspace backup preview loaded: ${parsed.storageSnapshot.length} local item${parsed.storageSnapshot.length === 1 ? '' : 's'}`);
        return;
      }
      if (!parsed.schema?.startsWith('phioffice369.project_manifest.')) {
        setStatus('Imported file is not a PhiOffice369 project manifest or workspace backup');
        return;
      }
      setImportedManifest(parsed);
      setImportedBackup(null);
      setStatus(`Imported preview: ${parsed.title ?? 'Untitled manifest'}`);
    } catch {
      setStatus('Could not read that manifest or backup JSON');
    } finally {
      event.target.value = '';
    }
  }

  function handleArtifactKeyDown(event, artifact) {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      selectArtifact(artifact);
    }
  }

  return (
    <section className="phivault-lite section-block fade-in">
      <div className="vault-hero panel">
        <FolderLock aria-hidden="true" />
        <div>
          <p className="eyebrow">PhiVault-lite</p>
          <h2>Local project continuity</h2>
          <p>Scan browser-local drafts, grids, decks, and export receipts; organize them with local tags and project folders; then export project continuity JSON.</p>
          <p className="vault-status">{status}</p>
          {copyStatus && <p className="vault-copy-status">{copyStatus}</p>}
        </div>
        <div className="vault-actions">
          <button type="button" onClick={refreshArtifacts}><RefreshCw aria-hidden="true" /> Refresh scan</button>
          <button type="button" onClick={copyManifest}><ClipboardCopy aria-hidden="true" /> Copy manifest</button>
          <button type="button" onClick={triggerImport}><Upload aria-hidden="true" /> Import preview</button>
          <button type="button" onClick={exportManifest}><Download aria-hidden="true" /> Export manifest</button>
          <button type="button" onClick={exportWorkspaceBackup}><Download aria-hidden="true" /> Backup workspace</button>
          <input ref={fileInputRef} className="vault-file-input" type="file" accept="application/json,.json" onChange={importManifest} />
        </div>
      </div>

      <div className="vault-grid">
        <aside className="panel vault-summary">
          <ShieldCheck aria-hidden="true" />
          <h3>Manifest envelope</h3>
          <code>{manifest.schema}</code>
          <div className="vault-stat-grid">
            <div><strong>{artifacts.length}</strong><span>items</span></div>
            <div><strong>{filteredArtifacts.length}</strong><span>shown</span></div>
            <div><strong>{exportReceiptCount}</strong><span>exports</span></div>
            <div><strong>{projectFolderCount}</strong><span>folders</span></div>
          </div>
          <p>Nothing is uploaded. This view only reads local browser storage created by the prototype and imported JSON files you select.</p>

          {storageStatus && (
            <div className="storage-status-card">
              <Database aria-hidden="true" />
              <div>
                <h3>Storage status</h3>
                <p>{getStorageStatusMessage(storageStatus)}</p>
                <div className="storage-status-grid">
                  <span>Detected: {storageStatus.detectedBackend}</span>
                  <span>Adapter: {storageStatus.activeAdapterId}</span>
                  <span>Snapshot items: {storageStatus.snapshotCount}</span>
                  <span>IndexedDB ready: {storageStatus.readyForIndexedDbMigration ? 'yes' : 'no'}</span>
                </div>
                <div className="storage-migration-actions">
                  <button type="button" onClick={planIndexedDbMigration}>Plan IndexedDB migration</button>
                  <button type="button" onClick={copyMissingToIndexedDb}>Copy missing safely</button>
                  <button type="button" onClick={copyMigrationReport}>Copy report</button>
                  <button type="button" onClick={exportMigrationReport}>Export report</button>
                </div>
                {migrationSummary && (
                  <div className="storage-migration-summary">
                    <span>Source: {migrationSummary.sourceCount}</span>
                    <span>Missing: {migrationSummary.missingInTargetCount}</span>
                    <span>Synced: {migrationSummary.alreadySyncedCount}</span>
                    <span>Conflicts: {migrationSummary.conflictCount}</span>
                    <span>{migrationSummary.safeToCopyWithoutOverwrite ? 'Safe copy path clear' : 'Conflicts require review'}</span>
                  </div>
                )}
                {migrationConflictKeys.length > 0 && (
                  <div className="storage-conflict-preview">
                    <h4>Conflict keys</h4>
                    {migrationConflictKeys.map((key) => <code key={key}>{key}</code>)}
                  </div>
                )}
                {migrationResult && (
                  <p className="storage-migration-result">Last copy: {migrationResult.appliedCount} copied · {migrationResult.skippedCount} skipped · {migrationResult.conflictCount} conflicts</p>
                )}
              </div>
            </div>
          )}

          {importedBackup && (
            <div className="import-preview backup-preview">
              <h3>Workspace backup preview</h3>
              <p>{importedBackup.source}</p>
              <code>{importedBackup.schema}</code>
              <span>{importedBackup.storageSnapshot.length} local items</span>
              <button type="button" onClick={restoreImportedBackup}>Restore backup into browser storage</button>
            </div>
          )}

          {importedManifest && (
            <div className="import-preview">
              <h3>Imported preview</h3>
              <p>{importedManifest.title}</p>
              <code>{importedManifest.schema}</code>
              <span>{importedManifest.artifacts?.length ?? 0} artifacts</span>
            </div>
          )}
        </aside>

        <section className="panel vault-artifacts">
          <div className="vault-section-heading">
            <div>
              <p className="eyebrow">Local continuity</p>
              <h2>Detected drafts, grids, decks, and exports</h2>
            </div>
          </div>

          <div className="vault-filter-panel">
            <label className="vault-search-box">
              <Search aria-hidden="true" />
              <input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search title, app, kind, label, tag, folder, path, status..." />
            </label>
            <div className="vault-select-row three-selects">
              <label>
                <span>App</span>
                <select value={appFilter} onChange={(event) => setAppFilter(event.target.value)}>
                  {appOptions.map((option) => <option key={option} value={option}>{option === 'all' ? 'All apps' : option}</option>)}
                </select>
              </label>
              <label>
                <span>Kind</span>
                <select value={kindFilter} onChange={(event) => setKindFilter(event.target.value)}>
                  {kindOptions.map((option) => <option key={option} value={option}>{option === 'all' ? 'All kinds' : option}</option>)}
                </select>
              </label>
              <label>
                <span>Project</span>
                <select value={projectFilter} onChange={(event) => setProjectFilter(event.target.value)}>
                  {projectOptions.map((option) => <option key={option} value={option}>{option === 'all' ? 'All folders' : option}</option>)}
                </select>
              </label>
              <button type="button" onClick={resetFilters}>Reset filters</button>
            </div>
          </div>

          {exportTimeline.length > 0 && (
            <section className="receipt-timeline">
              <div className="receipt-timeline-heading">
                <div>
                  <p className="eyebrow">Export receipt timeline</p>
                  <h3>Recent local exports</h3>
                </div>
                <span>{exportTimeline.length} receipt{exportTimeline.length === 1 ? '' : 's'}</span>
              </div>
              <div className="receipt-timeline-list">
                {exportTimeline.slice(0, 8).map(({ artifact, receipt }) => (
                  <article className="receipt-timeline-item" key={artifact.artifactId}>
                    <time>{formatExportTime(receipt.exportedAt)}</time>
                    <div>
                      <h3>{receipt.filename ?? artifact.title}</h3>
                      <p>{receipt.sourceApp} · {receipt.format} · {receipt.compatibility}</p>
                      <code>{receipt.artifactId}</code>
                    </div>
                  </article>
                ))}
              </div>
            </section>
          )}

          {selectedArtifact && (
            <section className="artifact-detail-drawer">
              <div className="artifact-detail-heading">
                <div>
                  <p className="eyebrow">Artifact detail</p>
                  <h3>{selectedArtifact.title}</h3>
                </div>
                <button type="button" className="detail-close-button" onClick={() => setSelectedArtifact(null)}><X aria-hidden="true" /> Close</button>
              </div>

              <div className="detail-metadata-grid">
                <div><span>App</span><strong>{detailValue(selectedArtifact.app)}</strong></div>
                <div><span>Kind</span><strong>{detailValue(selectedArtifact.kind)}</strong></div>
                <div><span>Status</span><strong>{detailValue(selectedArtifact.status)}</strong></div>
                <div><span>Project folder</span><strong>{detailValue(selectedArtifact.projectFolder)}</strong></div>
                <div><span>Source template</span><strong>{detailValue(selectedArtifact.sourceTemplateId)}</strong></div>
                <div><span>Updated</span><strong>{detailValue(selectedArtifact.metadata?.metadataUpdatedAt ?? selectedArtifact.updatedAt)}</strong></div>
              </div>

              <div className="detail-path-box">
                <span>Storage path</span>
                <code>{selectedArtifact.path}</code>
              </div>

              <div className="detail-label-row">
                {(selectedArtifact.labels?.length ? selectedArtifact.labels : ['no_labels']).map((label) => <span key={label}>{label}</span>)}
              </div>

              <div className="detail-tag-editor">
                <label>
                  <span>Local tags</span>
                  <input value={tagInput} onChange={(event) => setTagInput(event.target.value)} placeholder="client-work, launch, private" />
                </label>
                <p>Tags are stored as local metadata and included in exported manifests. They do not modify the original draft, grid, deck, or receipt.</p>
                <div className="detail-tag-actions">
                  <button type="button" onClick={saveSelectedTags}>Save tags</button>
                  <button type="button" onClick={clearSelectedTags}>Clear input</button>
                </div>
              </div>

              <div className="detail-tag-editor project-editor">
                <label>
                  <span>Project folder</span>
                  <input value={projectInput} onChange={(event) => setProjectInput(event.target.value)} placeholder="Client Launch, Home Ops, PHI369 Docs" />
                </label>
                <p>Project folders are local organization metadata. They are searchable, filterable, and included in exported manifests.</p>
                <div className="detail-tag-actions">
                  <button type="button" onClick={saveSelectedProjectFolder}>Save folder</button>
                  <button type="button" onClick={clearProjectInput}>Clear input</button>
                </div>
              </div>

              <div className="detail-label-row tag-row">
                {(selectedArtifact.tags?.length ? selectedArtifact.tags : ['no_tags']).map((tag) => <span key={tag}>{tag}</span>)}
                {selectedArtifact.projectFolder && <span>{selectedArtifact.projectFolder}</span>}
              </div>

              {selectedReceipt && (
                <div className="detail-receipt-card">
                  <h3>Receipt metadata</h3>
                  <div className="detail-metadata-grid compact">
                    <div><span>Filename</span><strong>{detailValue(selectedReceipt.filename)}</strong></div>
                    <div><span>Format</span><strong>{detailValue(selectedReceipt.format)}</strong></div>
                    <div><span>Source app</span><strong>{detailValue(selectedReceipt.sourceApp)}</strong></div>
                    <div><span>Compatibility</span><strong>{detailValue(selectedReceipt.compatibility)}</strong></div>
                    <div><span>Exported</span><strong>{detailValue(selectedReceipt.exportedAt)}</strong></div>
                    <div><span>Artifact id</span><strong>{detailValue(selectedReceipt.artifactId)}</strong></div>
                  </div>
                </div>
              )}

              <div className="detail-copy-actions">
                <button type="button" onClick={copySelectedArtifact}><ClipboardCopy aria-hidden="true" /> Copy artifact JSON</button>
                {selectedReceipt && <button type="button" onClick={copySelectedReceipt}><ClipboardCopy aria-hidden="true" /> Copy receipt JSON</button>}
              </div>
            </section>
          )}

          {artifacts.length === 0 ? (
            <div className="empty-vault">
              <Sparkles aria-hidden="true" />
              <h3>No local continuity items yet</h3>
              <p>Open a template, make a small edit, export a file, and return here to refresh the vault scan.</p>
            </div>
          ) : filteredArtifacts.length === 0 ? (
            <div className="empty-vault">
              <Sparkles aria-hidden="true" />
              <h3>No matching continuity items</h3>
              <p>Try clearing the search or changing the app/kind/project filters.</p>
            </div>
          ) : (
            <div className="artifact-groups">
              {Object.entries(groupedArtifacts).map(([app, appArtifacts]) => (
                <section className="artifact-group" key={app}>
                  <div className="artifact-group-heading">
                    <h3>{app}</h3>
                    <span>{appArtifacts.length} item{appArtifacts.length === 1 ? '' : 's'}</span>
                  </div>
                  <div className="artifact-list">
                    {appArtifacts.map((artifact) => (
                      <article
                        className={`artifact-row ${artifact.kind === 'export_receipt' ? 'export-row' : ''} ${selectedArtifact?.artifactId === artifact.artifactId ? 'selected' : ''}`}
                        key={artifact.artifactId}
                        role="button"
                        tabIndex={0}
                        onClick={() => selectArtifact(artifact)}
                        onKeyDown={(event) => handleArtifactKeyDown(event, artifact)}
                      >
                        <div>
                          <span>{artifact.app} · {artifact.kind}</span>
                          <h3>{artifact.title}</h3>
                          <p>{artifact.path}</p>
                        </div>
                        <div className="artifact-badges">
                          <span>{artifact.status}</span>
                          {artifact.projectFolder && <span>{artifact.projectFolder}</span>}
                          {artifact.receipts?.[0]?.format && <span>{artifact.receipts[0].format}</span>}
                          {artifact.labels.map((label) => <span key={label}>{label}</span>)}
                          {artifact.tags?.map((tag) => <span key={tag}>{tag}</span>)}
                        </div>
                      </article>
                    ))}
                  </div>
                </section>
              ))}
            </div>
          )}
        </section>
      </div>
    </section>
  );
}
