import { useMemo, useState } from 'react';
import { Download, FolderLock, RefreshCw, ShieldCheck, Sparkles } from 'lucide-react';
import { createArtifactManifestEntry, createProjectManifest } from '@phioffice369/core';
import './PhiVaultLite.css';

function canUseLocalStorage() {
  try {
    return typeof window !== 'undefined' && Boolean(window.localStorage);
  } catch {
    return false;
  }
}

function parseStoredValue(key) {
  try {
    return JSON.parse(window.localStorage.getItem(key));
  } catch {
    return null;
  }
}

function kindFromKey(key) {
  if (key.includes(':phiwrite:')) return { kind: 'document', app: 'PhiWrite' };
  if (key.includes(':phigrid:')) return { kind: 'grid', app: 'PhiGrid' };
  return { kind: 'vault_item', app: 'PhiVault' };
}

function titleFromDraft(key, value) {
  if (value?.title) return value.title;
  return key.split(':').at(-1) ?? 'Untitled artifact';
}

function scanLocalArtifacts() {
  if (!canUseLocalStorage()) return [];

  return Object.keys(window.localStorage)
    .filter((key) => key.startsWith('phioffice369:'))
    .map((key) => {
      const storedValue = parseStoredValue(key);
      const { kind, app } = kindFromKey(key);
      return createArtifactManifestEntry({
        artifactId: key.replaceAll(':', '_'),
        title: titleFromDraft(key, storedValue),
        kind,
        app,
        path: key,
        labels: storedValue?.activeLabelId ? [storedValue.activeLabelId] : [],
        sourceTemplateId: storedValue?.templateId ?? null,
        status: 'local-draft',
      });
    });
}

function downloadJson(filename, payload) {
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

export default function PhiVaultLite() {
  const [artifacts, setArtifacts] = useState(() => scanLocalArtifacts());
  const [status, setStatus] = useState('Local manifest ready');

  const manifest = useMemo(() => createProjectManifest({
    projectId: 'local_phioffice369_project',
    title: 'Local PhiOffice369 Workspace',
    description: 'Browser-local project manifest generated by PhiVault-lite.',
    owner: 'local-browser-user',
    tags: ['local-first', 'prototype', 'phioffice369'],
    artifacts,
  }), [artifacts]);

  function refreshArtifacts() {
    const nextArtifacts = scanLocalArtifacts();
    setArtifacts(nextArtifacts);
    setStatus(`Scanned ${nextArtifacts.length} local artifact${nextArtifacts.length === 1 ? '' : 's'}`);
  }

  function exportManifest() {
    downloadJson('phioffice369-local-project-manifest.json', manifest);
    setStatus('Project manifest exported');
  }

  return (
    <section className="phivault-lite section-block fade-in">
      <div className="vault-hero panel">
        <FolderLock aria-hidden="true" />
        <div>
          <p className="eyebrow">PhiVault-lite</p>
          <h2>Local project continuity</h2>
          <p>Scan browser-local PhiOffice369 drafts, collect artifact entries, and export a project manifest JSON.</p>
          <p className="vault-status">{status}</p>
        </div>
        <div className="vault-actions">
          <button type="button" onClick={refreshArtifacts}><RefreshCw aria-hidden="true" /> Refresh scan</button>
          <button type="button" onClick={exportManifest}><Download aria-hidden="true" /> Export manifest</button>
        </div>
      </div>

      <div className="vault-grid">
        <aside className="panel vault-summary">
          <ShieldCheck aria-hidden="true" />
          <h3>Manifest envelope</h3>
          <code>{manifest.schema}</code>
          <div className="vault-stat-grid">
            <div><strong>{artifacts.length}</strong><span>artifacts</span></div>
            <div><strong>{manifest.tags.length}</strong><span>tags</span></div>
          </div>
          <p>Nothing is uploaded. This view only reads local browser storage created by the prototype.</p>
        </aside>

        <section className="panel vault-artifacts">
          <div className="vault-section-heading">
            <div>
              <p className="eyebrow">Local artifacts</p>
              <h2>Detected drafts and grids</h2>
            </div>
          </div>

          {artifacts.length === 0 ? (
            <div className="empty-vault">
              <Sparkles aria-hidden="true" />
              <h3>No local artifacts yet</h3>
              <p>Open a template in PhiWrite-lite or PhiGrid-lite, make a small edit, and return here to refresh the vault scan.</p>
            </div>
          ) : (
            <div className="artifact-list">
              {artifacts.map((artifact) => (
                <article className="artifact-row" key={artifact.artifactId}>
                  <div>
                    <span>{artifact.app} · {artifact.kind}</span>
                    <h3>{artifact.title}</h3>
                    <p>{artifact.path}</p>
                  </div>
                  <div className="artifact-badges">
                    <span>{artifact.status}</span>
                    {artifact.labels.map((label) => <span key={label}>{label}</span>)}
                  </div>
                </article>
              ))}
            </div>
          )}
        </section>
      </div>
    </section>
  );
}
